#FROM https://gitee.com/oceanbase/obdeploy/blob/master/example/mini-local-example.yaml
oceanbase-ce:
  servers:
    - 127.0.0.1
  global:
    home_path: @OB_HOME_PATH@ # default: /root/ob
    devname: lo
    mysql_port: @OB_MYSQL_PORT@ # default: 2881
    rpc_port: @OB_RPC_PORT@ # default: 2882
    zone: zone1
    cluster_id: 1
    memory_limit: 8G
    system_memory: 4G
    stack_size: 512K
    cpu_count: 16
    cache_wash_threshold: 1G
    __min_full_resource_pool_memory: 268435456
    workers_per_cpu_quota: 10
    schema_history_expire_time: 1d
    net_thread_count: 4
    sys_bkgd_migration_retry_num: 3
    minor_freeze_times: 100
    enable_separate_sys_clog: 0
    enable_merge_by_turn: FALSE
    enable_auto_leader_switch: FALSE
    enable_one_phase_commit: FALSE
    weak_read_version_refresh_interval: 5s
    trace_log_slow_query_watermark: 1s
    large_query_threshold: 1s
    clog_sync_time_warn_threshold: 1s
    syslog_io_bandwidth_limit: 10M
    enable_sql_audit: FALSE
    enable_perf_event: FALSE
    clog_max_unconfirmed_log_count: 5000
    autoinc_cache_refresh_interval: 86400s
    cpu_quota_concurrency: 2
    datafile_size: 5G
    syslog_level: WARN
    enable_syslog_recycle: TRUE
    max_syslog_file_count: 2
    enable_early_lock_release: false tenant=all
    default_compress_func: lz4_1.0
    root_password: @OB_ROOT_PASSWORD@ # default: null
