name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-x86_64:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
  
    - name: Install environment
      shell: bash
      run: sudo apt-get install -y git wget rpm rpm2cpio cpio make build-essential binutils m4
  
    - name: Build project
      shell: bash
      run: | 
        bash build.sh init
        bash build.sh debug
        cd build_debug && make -j4

  centos-x86_64:
    runs-on: ubuntu-18.04
    container: centos:7
    steps:
    - uses: actions/checkout@v2

    - name: Install environment
      shell: bash
      run: yum install -y git wget rpm* cpio make glibc-devel glibc-headers binutils m4

    - name: Build project
      shell: bash
      run: |
        bash build.sh init
        bash build.sh debug
        cd build_debug && make -j4
        
