name: Compile

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix: 
        image: ['ubuntu:22.04', 'centos:7']
    runs-on: ubuntu-20.04
    container: ${{ matrix.image }}
    steps:
    - uses: actions/checkout@v3

    - name: Install ubuntu environment
      shell: bash
      if: ${{ startsWith(matrix.image, 'ubuntu') }}
      run: |
        export DEBIAN_FRONTEND=noninteractive
        apt-get update
        apt-get install -y git wget rpm rpm2cpio cpio make build-essential binutils m4 libtool-bin libncurses5
      
    - name: Install centos environment
      shell: bash
      if: ${{ startsWith(matrix.image, 'centos') }}
      run: yum install -y git wget rpm* cpio make glibc-devel glibc-headers binutils m4

    - name: Cache deps
      id: cache-deps
      uses: actions/cache@v3
      env:
        cache-name: cache-deps
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}-el7.x86_64-${{ hashFiles('deps/init/oceanbase.el7.x86_64.deps') }}
        path: deps/3rd
        enableCrossOsArchive: true
    
    - name: Build init
      run: bash build.sh init
      
    - name: Build project
      shell: bash
      run: |
        bash build.sh debug
        cd build_debug && make -j4
